version: 1
formatters:
  hemppa:
    format: '%(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: hemppa
    stream: ext://sys.stdout
loggers:
  hemppa:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
